version: "3.7"
services:
  postgresdb:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - postgresdb
    networks:
      - default
    ports:
      - "8080:8080"
volumes:
  data:
